[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FEMTISE = "0bd82848-28f8-4e57-bc39-0a3ec24854bf"
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
